import { FLAG_RATIO } from "./config.js";
import { minifyCss } from "./utils.js";

export function buildStylesheet(entries) {
  const baseRule = [
    "/* Generated by npm run build:package. Do not edit by hand. */",
    ".pf {",
    "  --pf-height: 1em;",
    "  display: inline-block;",
    `  width: calc(${FLAG_RATIO.width} / ${FLAG_RATIO.height} * var(--pf-height));`,
    "  height: var(--pf-height);",
    "  background-repeat: no-repeat;",
    "  background-position: center;",
    "  background-size: 100% 100%;",
    "  image-rendering: pixelated;",
    "  vertical-align: middle;",
    "}",
    "",
  ].join("\n");

  const flagRules = entries.map(
    (entry) => `.pf-${entry.slug} {\n  background-image: url("../flags/${entry.fileName}");\n}`
  );

  return `${baseRule}${flagRules.join("\n\n")}\n`;
}

export function buildMinifiedStylesheet(css) {
  return minifyCss(css);
}
